### ISSUE TITLE
Move writeable files to a specific path to support container volumens

### ISSUE THREAD

**Issue by felipet** [felipet/lacoctelera_backend#67]
The base container image shall keep a RO policy. All the files that are susceptible of being written need to be placed in a specific path. This way, we can specify a volume when running the application image within some containerisation environment (docker, podman).

**Comment by felipet** [comment]
This is achieved simply by means of using the following command to run the container using `podman`:

```bash
$ podman run -d --network host -v coctelera:/app/config ghcr.io/felipet/lacoctelera_backend:main
```

That will create (if it doesn't exist) the named volume `coctelera` in which the configuration files will be placed, thus it would be possible to modify those when needed. 

The remaining writeable file is the log, which can be placed within the same location or another and exported via an extra volume.

```toml
[application.log_settings]
tracing_level = "info"
log_output_file = "/app/config/lacoctelera_log"
```
